apiVersion: v2
name: octant
description: A Helm chart to deploy Octant (vmware-tanzu/octant) to Kubernetes

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 0.25.1

dependencies:
  - name: oauth2-proxy
    version: 6.2.2
    repository: https://oauth2-proxy.github.io/manifests
    condition: oauth2-proxy.enabled
